# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Template-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Template-iOS
  pod 'GoogleSignIn'
end
